server:
  port: 8080
spring:
  application:
    name: reggie_take_out

  mail:
    host: smtp.qq.com  # 发送邮件的服务器地址
    username: 1461027098@qq.com # 登录qq邮箱的账号
    password: mjflqskhbqgjjgeg  # 开启 IMAP/SMTP服务 获得的授权码,而不是qq邮箱的登录密码
    default-encoding: UTF-8

  redis:
    host: localhost # 本地IP 或是 虚拟机IP
    port: 6379 #默认端口
      #    password: root
    database: 0  # 默认使用 0号db
  cache:
    redis:
      time-to-live: 1800000  # 设置缓存数据的过期时间，30分钟 单位(ms)

  shardingsphere:
    datasource:
      names:
        master,slave
      # 主数据源
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.157.137:3306/reggie?characterEncoding=utf-8&useSSL=false
        username: root
        password: hj314159
      # 从数据源
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.157.134:3306/reggie?characterEncoding=utf-8&useSSL=false
        username: root
        password: hj314159
    masterslave:
      # 读写分离配置
      load-balance-algorithm-type: round_robin
      # 最终的数据源名称
      name: dataSource
      # 主库数据源名称
      master-data-source-name: master
      # 从库数据源名称列表，多个逗号分隔
      slave-data-source-names: slave
    props:
      sql:
        show: true #开启SQL显示，默认false，开启后能在控制台输出SQL

  main:
    allow-bean-definition-overriding: true

#使用mybatis-plus
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

reggie:
  path: D:\workspace\reggie_take_out\src\main\resources\backend\images\dishes\


